### ISSUE TITLE
Setup MKDocs for compas-developers

### ISSUE THREAD

**Issue by pascalwilbrink** [com-pas/compas-developers#1]
We need a central place where we can host developers documentation.

By using [MKDocs](https://www.mkdocs.org/), we can write docs in markdown and translate it to static HTML pages that can be hosted on GitHub Pages.

**Comment by benvantende** [comment]
Using the subdomain developers.compas.energy

**Comment by benvantende** [comment]
@pascalwilbrink shall we close this and open a more generic issue because we most probably will not be using MkDocs? I can include a story as well. WDYT?

**Comment by benvantende** [comment]
Closing for a more generic issue
